name: Deploy Nyx  campaign agent    to the Development environment
run-name:  Nyx campaign agent   Dev Server Deployer
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Deploy via SSH
      - name: Deploy Code to Server
        uses: appleboy/ssh-action@v1.2.0
        env:
            GH_PERSONAL_ACCESS_TOKEN: ${{secrets.NYX_CAMPAIGN_REPO_GITHUB_TOKEN}}
        
            
        with:
          host: ${{ vars.DEV_SERVER_SSH_HOST_IP }}
          envs: GH_PERSONAL_ACCESS_TOKEN
          username: ${{ vars.DEV_SERVER_SSH_USER }}
          password: ${{ secrets.DEV_SERVER_PASS }}
          debug: true
          script_path:  scripts/deploy-dev.sh
          
